userStory:
  role: "[role]"
  function: "[function]"
  benefit: "[benefit]"

detailsAndAssumptions: "[Document any relevant information you know]"

acceptanceCriteria:
  given: "[some context]"
  when: "[certain action is taken]"
  then: "[the outcome of action is observed]"