## User Story

**As a** [role],  
**I want** [function],  
**So that** [benefit].  

### Details and Assumptions
* [Document any relevant information you know].  

### Acceptance Criteria
   gherkin
Given [some context],
When [certain action is taken],
Then [the outcome of action is observed].
